%% FIGURE 3: Average achievable rate vs normalized source transmit power
% Analytical average rate from Eq. (44) + direct Monte-Carlo validation
% High-source-power rate ceiling from Eq. (45)
%
% IMPORTANT:
% 1) Run the revised Figure-2 script FIRST.
% 2) This script loads JSAC_Master_Numerical_Data.mat produced by Fig. 2.
% 3) It therefore uses EXACTLY the same:
%       - optimized MA/PA deterministic gains,
%       - fixed-position benchmark,
%       - outage-optimal rho values versus normalized source transmit power,
%       - normalized-source-transmit-power grid,
%       - Log-alpha-mu normalization constants.
% 4) The rate is NOT reoptimized for the rate objective.  This matches
%    the manuscript: Fig. 3 evaluates the rate of the outage-optimized
%    designs used in Fig. 2.
%
% FINAL FIGURE STYLE:
% - Main analytical curves: 0.90 pt.
% - Ceiling lines: 0.85 pt.
% - Open simulation circles: analytical lines remain visible through them.
% - Single-column IEEE width: 3.50 in.
% - Axis labels contain both the physical name and mathematical symbol.

clear; clc; close all;

%% ------------------------------------------------------------------------
% 1) LOAD THE MASTER DATA GENERATED BY FIGURE 2
% -------------------------------------------------------------------------
% Resolve this script's own folder so shared data are found reliably.
thisScript = mfilename('fullpath');
if isempty(thisScript)
    thisDir = pwd;
else
    thisDir = fileparts(thisScript);
end
masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

% If the shared master data do not yet exist, generate them automatically
% from the finalized Figure-2 program in the same folder.
if ~isfile(masterFile)
    fig2File = fullfile(thisDir,'JSAC_Figure02_FINAL.m');

    if ~isfile(fig2File)
        error(['JSAC_Master_Numerical_Data.mat was not found, and ', ...
               'JSAC_Figure02_FINAL.m is not in the same folder. ', ...
               'Keep all finalized Figure 2-9 programs together.']);
    end

    disp('Shared numerical data were not found.');
    disp('Running finalized Figure 2 first to generate them...');
    run(fig2File);
    close all;

    % Re-establish this script's folder after returning from Figure 2.
    thisScript = mfilename('fullpath');
    if isempty(thisScript)
        thisDir = pwd;
    else
        thisDir = fileparts(thisScript);
    end
    masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

    if ~isfile(masterFile)
        error(['Figure 2 completed, but JSAC_Master_Numerical_Data.mat ', ...
               'was not created in the script folder.']);
    end
end

load(masterFile);

requiredVars = { ...
    'snrDb', ...
    'rho_MA','rho_PA','rho_FIX', ...
    'Omega1_MA','Omega2_MA', ...
    'Omega1_PA','Omega2_PA', ...
    'M1','M2'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k},'var')
        error('Required variable "%s" is missing from %s.', ...
              requiredVars{k},masterFile);
    end
end

Omega1_FIX = 1;
Omega2_FIX = 1;

%% ------------------------------------------------------------------------
% 2) TABLE-II / MANUSCRIPT PARAMETERS
% -------------------------------------------------------------------------
sigmaR2 = 1;
sigmaD2 = 1;

Pmax = sigmaD2*10^(13/10);      % Pmax/sigma_D^2 = 13 dB
bEH  = sigmaR2*10^(10/10);      % bEH/sigma_R^2 = 10 dB
aEH  = 0.5/sigmaR2;             % aEH*sigma_R^2 = 0.5
xi0  = 1/(1+exp(aEH*bEH));

% Default Log-alpha-mu tuple
alpha1 = 2; beta1 = 1; mu1 = 2; s1 = 0.5;
alpha2 = 2; beta2 = 1; mu2 = 2; s2 = 0.5;

Nmc = 1e6;

% Adaptive generalized Gauss-Laguerre orders for Eq. (44).
% The final numerical value is checked between successive orders.
GGLorders = [12 16 24 32 48 64 96 128];

% Internal convergence criterion for the rate representation.
rateRelTol = 1e-9;
rateAbsTol = 1e-11;

p.alpha1 = alpha1;
p.beta1  = beta1;
p.mu1    = mu1;
p.s1     = s1;
p.M1     = M1;

p.alpha2 = alpha2;
p.beta2  = beta2;
p.mu2    = mu2;
p.s2     = s2;
p.M2     = M2;

p.sigmaR2 = sigmaR2;
p.sigmaD2 = sigmaD2;

p.Pmax = Pmax;
p.bEH  = bEH;
p.aEH  = aEH;
p.xi0  = xi0;

%% ------------------------------------------------------------------------
% 3) ANALYTICAL AVERAGE RATE — EQ. (44)
% -------------------------------------------------------------------------
nSNR = numel(snrDb);

Rana_MA  = zeros(1,nSNR);
Rana_PA  = zeros(1,nSNR);
Rana_FIX = zeros(1,nSNR);

Nused_MA  = zeros(1,nSNR);
Nused_PA  = zeros(1,nSNR);
Nused_FIX = zeros(1,nSNR);

fprintf('\n===== ANALYTICAL AVERAGE RATE: EQ. (44) =====\n');

for k = 1:nSNR

    Ps = sigmaR2*10^(snrDb(k)/10);

    [Rana_MA(k),Nused_MA(k)] = adaptiveAverageRateGGL( ...
        Ps,rho_MA(k),Omega1_MA,Omega2_MA, ...
        p,GGLorders,rateRelTol,rateAbsTol);

    [Rana_PA(k),Nused_PA(k)] = adaptiveAverageRateGGL( ...
        Ps,rho_PA(k),Omega1_PA,Omega2_PA, ...
        p,GGLorders,rateRelTol,rateAbsTol);

    [Rana_FIX(k),Nused_FIX(k)] = adaptiveAverageRateGGL( ...
        Ps,rho_FIX(k),Omega1_FIX,Omega2_FIX, ...
        p,GGLorders,rateRelTol,rateAbsTol);

    fprintf(['SNR=%2d dB | MA %.6f (N=%d) | ', ...
             'PA %.6f (N=%d) | Fixed %.6f (N=%d)\n'], ...
             snrDb(k), ...
             Rana_MA(k),Nused_MA(k), ...
             Rana_PA(k),Nused_PA(k), ...
             Rana_FIX(k),Nused_FIX(k));
end

%% ------------------------------------------------------------------------
% 4) MONTE-CARLO VALIDATION — DIRECT EQS. (7) AND (10)
% -------------------------------------------------------------------------
% Use the same random seed as the Fig. 2 script so that the residual-fading
% samples are reproducible across the numerical section.
rng(20260910,'twister');

r1 = @(u) ((1+beta1*u/mu1).^(1/beta1)-s1).^(1/alpha1) ...
          -(1-s1)^(1/alpha1);

r2 = @(u) ((1+beta2*u/mu2).^(1/beta2)-s2).^(1/alpha2) ...
          -(1-s2)^(1/alpha2);

U1mc = randg(mu1,Nmc,1);
U2mc = randg(mu2,Nmc,1);

Z1mc = r1(U1mc).^2/M1;
Z2mc = r2(U2mc).^2/M2;

Rsim_MA  = zeros(1,nSNR);
Rsim_PA  = zeros(1,nSNR);
Rsim_FIX = zeros(1,nSNR);

fprintf('\n===== MONTE-CARLO AVERAGE RATE =====\n');

for k = 1:nSNR

    Ps = sigmaR2*10^(snrDb(k)/10);

    Rsim_MA(k) = directMonteCarloRate( ...
        Ps,rho_MA(k),Omega1_MA,Omega2_MA,Z1mc,Z2mc,p);

    Rsim_PA(k) = directMonteCarloRate( ...
        Ps,rho_PA(k),Omega1_PA,Omega2_PA,Z1mc,Z2mc,p);

    Rsim_FIX(k) = directMonteCarloRate( ...
        Ps,rho_FIX(k),Omega1_FIX,Omega2_FIX,Z1mc,Z2mc,p);

    fprintf(['SNR=%2d dB | MA %.6f | PA %.6f | Fixed %.6f\n'], ...
        snrDb(k),Rsim_MA(k),Rsim_PA(k),Rsim_FIX(k));
end

%% ------------------------------------------------------------------------
% 5) HIGH-SOURCE-POWER RATE CEILINGS — EQ. (45)
% -------------------------------------------------------------------------
[Rceil_MA,Nceil_MA] = adaptiveRateCeilingGGL( ...
    Omega2_MA,p,GGLorders,rateRelTol,rateAbsTol);

[Rceil_PA,Nceil_PA] = adaptiveRateCeilingGGL( ...
    Omega2_PA,p,GGLorders,rateRelTol,rateAbsTol);

% Computed for checking, although the fixed ceiling is not plotted to keep
% Fig. 3 consistent with the manuscript and visually uncluttered.
[Rceil_FIX,Nceil_FIX] = adaptiveRateCeilingGGL( ...
    Omega2_FIX,p,GGLorders,rateRelTol,rateAbsTol);

fprintf('\n===== HIGH-SOURCE-POWER RATE CEILINGS: EQ. (45) =====\n');
fprintf('MA    = %.8f bit/s/Hz (N=%d)\n',Rceil_MA,Nceil_MA);
fprintf('PA    = %.8f bit/s/Hz (N=%d)\n',Rceil_PA,Nceil_PA);
fprintf('Fixed = %.8f bit/s/Hz (N=%d)\n',Rceil_FIX,Nceil_FIX);

fprintf('\n===== MAX |ANALYSIS - SIMULATION| =====\n');
fprintf('MA    = %.4e bit/s/Hz\n',max(abs(Rana_MA-Rsim_MA)));
fprintf('PA    = %.4e bit/s/Hz\n',max(abs(Rana_PA-Rsim_PA)));
fprintf('Fixed = %.4e bit/s/Hz\n',max(abs(Rana_FIX-Rsim_FIX)));

%% ------------------------------------------------------------------------
% 6) REVISED IEEE-STYLE FIGURE 3
% -------------------------------------------------------------------------
% Keep exactly the same visual language as revised Fig. 2.
cMA  = [1.00 0.00 0.00];
cPA  = [0.00 0.00 1.00];
cFIX = [0.00 0.00 0.00];
cSIM = [0.00 0.00 0.00];

fig = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 3.50 2.55]);

ax = axes(fig);
hold(ax,'on');
box(ax,'on');

%% Analytical rate curves
hMA = plot(ax, ...
    snrDb,Rana_MA,'-', ...
    'Color',cMA, ...
    'LineWidth',0.90, ...
    'DisplayName','Optimized MA');

hPA = plot(ax, ...
    snrDb,Rana_PA,'--', ...
    'Color',cPA, ...
    'LineWidth',0.90, ...
    'DisplayName','Optimized PA');

hFIX = plot(ax, ...
    snrDb,Rana_FIX,':', ...
    'Color',cFIX, ...
    'LineWidth',0.90, ...
    'DisplayName','Fixed positions');

%% Saturation-limited rate ceilings
hCeilMA = plot(ax, ...
    snrDb,Rceil_MA*ones(size(snrDb)),'-.', ...
    'Color',cMA, ...
    'LineWidth',0.85, ...
    'DisplayName','MA ceiling');

hCeilPA = plot(ax, ...
    snrDb,Rceil_PA*ones(size(snrDb)),'-.', ...
    'Color',cPA, ...
    'LineWidth',0.85, ...
    'DisplayName','PA ceiling');

%% Monte-Carlo markers
% Open markers let the analytical curves remain visible through each circle.
mk = 1:2:nSNR;                       % every 4 dB

plot(ax, ...
    snrDb(mk),Rsim_MA(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

plot(ax, ...
    snrDb(mk),Rsim_PA(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

plot(ax, ...
    snrDb(mk),Rsim_FIX(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

%% Dummy simulation handle for legend
hSim = plot(ax, ...
    NaN,NaN,'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'DisplayName','Simulation');

%% Axis labels
xlabel(ax, ...
    'Normalized source transmit power (dB)', ...
    'Interpreter','latex', ...
        'FontSize',10);

ylabel(ax, ...
    'Average rate (bit/s/Hz)', ...
    'Interpreter','latex', ...
        'FontSize',10);

xlim(ax,[0 40]);
xticks(ax,0:5:40);

% Choose the upper limit automatically so the highest ceiling is visible
% without excessive blank space.
yTop = 1.08*max([Rceil_MA,Rceil_PA,Rceil_FIX, ...
                Rana_MA,Rana_PA,Rana_FIX]);
ylim(ax,[0 yTop]);

% Use clean 0.5-bit/s/Hz major tick spacing whenever possible.
ytopTick = ceil(yTop/0.5)*0.5;
yticks(ax,0:0.5:ytopTick);

%% Clean IEEE-style axes/grid
set(ax, ...
    'FontName','Times New Roman', ...
    'FontSize',8, ...
    'TickLabelInterpreter','latex', ...
    'LineWidth',0.70, ...
    'TickDir','in', ...
    'XGrid','on', ...
    'YGrid','on', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'GridAlpha',0.14, ...
    'Layer','top');

%% Legend
lgd = legend(ax, ...
    [hMA hPA hFIX hCeilMA hCeilPA hSim], ...
    'Location','northwest', ...
    'Interpreter','latex', ...
    'FontSize',7, ...
    'Box','on');

lgd.LineWidth = 0.55;
lgd.ItemTokenSize = [18 8];

%% Vector export
set(fig,'Renderer','painters');

exportgraphics(fig, ...
    'Fig3_AverageRate_Analysis_Simulation_Revised.pdf', ...
    'ContentType','vector');

exportgraphics(fig, ...
    'Fig3_AverageRate_Analysis_Simulation_Revised.png', ...
    'Resolution',600);

%% ------------------------------------------------------------------------
% 7) APPEND FIGURE-3 RESULTS TO THE MASTER DATA FILE
% -------------------------------------------------------------------------
save(masterFile, ...
    'Rana_MA','Rana_PA','Rana_FIX', ...
    'Rsim_MA','Rsim_PA','Rsim_FIX', ...
    'Rceil_MA','Rceil_PA','Rceil_FIX', ...
    'Nused_MA','Nused_PA','Nused_FIX', ...
    'Nceil_MA','Nceil_PA','Nceil_FIX', ...
    '-append');

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function [Rbest,Nused] = adaptiveAverageRateGGL( ...
    Ps,rho,Omega1,Omega2,p,orders,relTol,absTol)
% Adaptive finite-order evaluation of the exact infinite-limit
% generalized Gauss-Laguerre representation in Eq. (44).

prev = NaN;
Rbest = NaN;
Nused = orders(end);

for ii = 1:numel(orders)

    N = orders(ii);

    [t1,w1] = generalizedGaussLaguerre(N,p.mu1-1);
    [t2,w2] = generalizedGaussLaguerre(N,p.mu2-1);

    Rnow = averageRateGGL( ...
        Ps,rho,Omega1,Omega2,p,t1,w1,t2,w2);

    if ii > 1
        err = abs(Rnow-prev);
        tol = absTol + relTol*abs(Rnow);

        if err <= tol
            Rbest = Rnow;
            Nused = N;
            return;
        end
    end

    prev = Rnow;
    Rbest = Rnow;
end

warning(['Rate quadrature convergence target was not reached ', ...
         'by N=%d. Highest-order result is used.'],orders(end));

end

%% ------------------------------------------------------------------------

function Rbar = averageRateGGL( ...
    Ps,rho,Omega1,Omega2,p,t1,w1,t2,w2)
% Eq. (44) at finite generalized Gauss-Laguerre order.

r1 = inverseLogAlphaMu(t1,p.alpha1,p.beta1,p.mu1,p.s1);
r2 = inverseLogAlphaMu(t2,p.alpha2,p.beta2,p.mu2,p.s2);

z1 = r1.^2/p.M1;
z2 = r2.^2/p.M2;

x = Omega1*z1(:);                 % N1 x 1
y = Omega2*z2(:).';               % 1 x N2

kappa = (1-rho)*Ps/p.sigmaR2;

Pin = rho*Ps*x;
PH = EHmap(Pin,p);
nu = PH/p.sigmaD2;

gamma1 = kappa*x;                 % N1 x 1
gamma2 = nu.*y;                   % N1 x N2

gammaE2E = ...
    (gamma1.*gamma2)./(gamma1+gamma2+1);

kernel = log2(1+gammaE2E);

Rbar = ...
    (w1(:).'*kernel*w2(:)) / ...
    (2*gamma(p.mu1)*gamma(p.mu2));

end

%% ------------------------------------------------------------------------

function Rbar = directMonteCarloRate( ...
    Ps,rho,Omega1,Omega2,Z1,Z2,p)
% Direct Monte-Carlo evaluation of
% 0.5*E[log2(1+gamma_e2e)] using Eqs. (7)-(10).

X = Omega1*Z1;
Y = Omega2*Z2;

Pin = rho*Ps.*X;
PH = EHmap(Pin,p);

gamma1 = (1-rho)*Ps.*X/p.sigmaR2;
gamma2 = PH.*Y/p.sigmaD2;

gammaE2E = ...
    (gamma1.*gamma2)./(gamma1+gamma2+1);

Rbar = 0.5*mean(log2(1+gammaE2E));

end

%% ------------------------------------------------------------------------

function [Rceil,Nused] = adaptiveRateCeilingGGL( ...
    Omega2,p,orders,relTol,absTol)
% Adaptive finite-order evaluation of Eq. (45).

prev = NaN;
Rceil = NaN;
Nused = orders(end);

for ii = 1:numel(orders)

    N = orders(ii);

    [t2,w2] = generalizedGaussLaguerre(N,p.mu2-1);

    r2 = inverseLogAlphaMu( ...
        t2,p.alpha2,p.beta2,p.mu2,p.s2);

    z2 = r2.^2/p.M2;
    y = Omega2*z2;

    val = ...
        (w2(:).'*log2(1 + (p.Pmax/p.sigmaD2)*y(:))) / ...
        (2*gamma(p.mu2));

    if ii > 1
        err = abs(val-prev);
        tol = absTol + relTol*abs(val);

        if err <= tol
            Rceil = val;
            Nused = N;
            return;
        end
    end

    prev = val;
    Rceil = val;
end

warning(['Rate-ceiling quadrature convergence target was not reached ', ...
         'by N=%d. Highest-order result is used.'],orders(end));

end

%% ------------------------------------------------------------------------

function r = inverseLogAlphaMu(t,alpha,beta,mu,s)
% Eq. (38)
r = ...
    ((1 + beta*t/mu).^(1/beta) - s).^(1/alpha) ...
    - (1-s)^(1/alpha);
end

%% ------------------------------------------------------------------------

function PH = EHmap(Pin,p)
% Eq. (7)

PH = ...
    (p.Pmax./(1+exp(-p.aEH*(Pin-p.bEH))) ...
    -p.Pmax*p.xi0)/(1-p.xi0);

PH = max(PH,0);
end

%% ------------------------------------------------------------------------

function [x,w] = generalizedGaussLaguerre(N,alphaLag)
% N-point generalized Gauss-Laguerre rule for
%
%   integral_0^Inf x^alphaLag exp(-x) f(x) dx
%
% valid for alphaLag > -1.
%
% Golub-Welsch construction:
% diagonal       = 2n-1+alphaLag
% off-diagonal   = sqrt(n(n+alphaLag))
% weights sum to Gamma(alphaLag+1).

if alphaLag <= -1
    error('Generalized Gauss-Laguerre requires alphaLag > -1.');
end

n = (1:N).';

d = 2*n - 1 + alphaLag;

k = (1:N-1).';
e = sqrt(k.*(k+alphaLag));

J = diag(d) + diag(e,1) + diag(e,-1);

[V,D] = eig(J,'vector');

[x,idx] = sort(D);
V = V(:,idx);

w = gamma(alphaLag+1)*(V(1,:).').^2;

end
