%% FIGURE 5: Maximum asymptotically feasible rate vs EH saturation power
% Analytical result from Eq. (35) + Monte-Carlo validation of the
% high-source-power limiting channel in Eqs. (33)-(34).
%
% Figure quantity:
%
%   R0,max^(chi)(epsilon)
%
% for epsilon = 10^(-3), versus Pmax/sigma_D^2.
%
% Analytical expression (Eq. 35):
%
%   R0,max = 1/2 log2[1 + (Pmax*Omega2,eff/sigma_D^2) F_Z2^{-1}(epsilon)]
%
% Monte-Carlo validation:
%   At high source power,
%
%       gamma_e2e -> Pmax * Omega2 * Z2 / sigma_D^2.
%
%   Therefore the largest target rate satisfying the empirical outage
%   requirement epsilon is obtained from the empirical epsilon-quantile
%   of gamma_e2e:
%
%       R0,max,MC = 1/2 log2(1 + quantile(gamma_inf,epsilon)).
%
% IMPORTANT:
% 1) Run JSAC_Figure02_FINAL.m first.
% 2) This script loads JSAC_Master_Numerical_Data.mat.
% 3) It therefore uses EXACTLY the same optimized destination-side gains
%    as Figs. 2-4.
% 4) No source-side gain or power-splitting parameter appears in the
%    high-source-power limit, consistent with Eq. (34).
%
% IEEE-style formatting:
% - analytical curves: 0.90 pt
% - open simulation circles: 3.8 pt
% - one-column width: 3.50 in
% - restrained MA / PA / fixed line styles and colors

clear; clc; close all;

%% ------------------------------------------------------------------------
% 1) LOAD MASTER DATA GENERATED BY FIGURE 2
% -------------------------------------------------------------------------
% Resolve this script's own folder so shared data are found reliably.
thisScript = mfilename('fullpath');
if isempty(thisScript)
    thisDir = pwd;
else
    thisDir = fileparts(thisScript);
end
masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

% If the shared master data do not yet exist, generate them automatically
% from the finalized Figure-2 program in the same folder.
if ~isfile(masterFile)
    fig2File = fullfile(thisDir,'JSAC_Figure02_FINAL.m');

    if ~isfile(fig2File)
        error(['JSAC_Master_Numerical_Data.mat was not found, and ', ...
               'JSAC_Figure02_FINAL.m is not in the same folder. ', ...
               'Keep all finalized Figure 2-9 programs together.']);
    end

    disp('Shared numerical data were not found.');
    disp('Running finalized Figure 2 first to generate them...');
    run(fig2File);
    close all;

    % Re-establish this script's folder after returning from Figure 2.
    thisScript = mfilename('fullpath');
    if isempty(thisScript)
        thisDir = pwd;
    else
        thisDir = fileparts(thisScript);
    end
    masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

    if ~isfile(masterFile)
        error(['Figure 2 completed, but JSAC_Master_Numerical_Data.mat ', ...
               'was not created in the script folder.']);
    end
end

load(masterFile);

requiredVars = { ...
    'Omega2_MA', ...
    'Omega2_PA', ...
    'M2'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k},'var')
        error('Required variable "%s" is missing from %s.', ...
              requiredVars{k},masterFile);
    end
end

Omega2_FIX = 1;

%% ------------------------------------------------------------------------
% 2) PARAMETERS
% -------------------------------------------------------------------------
sigmaD2 = 1;

% Default second-hop Log-alpha-mu tuple
alpha2 = 2;
beta2  = 1;
mu2    = 2;
s2     = 0.5;

epsilon = 1e-3;
Nmc = 1e6;

% Normalized EH saturation-power range
PmaxDb = 0:2:40;
PmaxLin = sigmaD2*10.^(PmaxDb/10);

%% ------------------------------------------------------------------------
% 3) EXACT ANALYTICAL epsilon-QUANTILE OF Z2
% -------------------------------------------------------------------------
% Eq. (13):
%
%   F_Z2(z) = P_Gamma(mu2, mu2*Psi2(sqrt(M2 z))).
%
% Thus,
%
%   u_epsilon = P_Gamma^{-1}(mu2,epsilon),
%
% and inversion of the implicit Log-alpha-mu mapping gives
%
%   F_Z2^{-1}(epsilon) = r2(u_epsilon)^2 / M2.
%
uEps = gammaincinv(epsilon,mu2,'lower');

rEps = ...
    ((1 + beta2*uEps/mu2).^(1/beta2) - s2).^(1/alpha2) ...
    - (1-s2)^(1/alpha2);

zEps = rEps.^2/M2;

fprintf('\n===== FIG. 5: ANALYTICAL LOWER-TAIL QUANTILE =====\n');
fprintf('epsilon              = %.3e\n',epsilon);
fprintf('F_Z2^{-1}(epsilon)   = %.10e\n',zEps);

%% ------------------------------------------------------------------------
% 4) ANALYTICAL MAXIMUM ASYMPTOTICALLY FEASIBLE RATE — EQ. (35)
% -------------------------------------------------------------------------
Rmax_MA = 0.5*log2( ...
    1 + (PmaxLin*Omega2_MA/sigmaD2)*zEps);

Rmax_PA = 0.5*log2( ...
    1 + (PmaxLin*Omega2_PA/sigmaD2)*zEps);

Rmax_FIX = 0.5*log2( ...
    1 + (PmaxLin*Omega2_FIX/sigmaD2)*zEps);

%% ------------------------------------------------------------------------
% 5) MONTE-CARLO VALIDATION OF THE HIGH-POWER LIMIT
% -------------------------------------------------------------------------
% Generate the same unit-mean Log-alpha-mu second-hop fading law.
rng(20260910,'twister');

r2 = @(u) ...
    ((1+beta2*u/mu2).^(1/beta2)-s2).^(1/alpha2) ...
    -(1-s2)^(1/alpha2);

U2mc = randg(mu2,Nmc,1);
Z2mc = r2(U2mc).^2/M2;

% Empirical lower-tail quantile of Z2.
% This is the direct Monte-Carlo counterpart of F_Z2^{-1}(epsilon).
zEpsMC = empiricalQuantile(Z2mc,epsilon);

fprintf('\n===== MONTE-CARLO LOWER-TAIL QUANTILE =====\n');
fprintf('Empirical F_Z2^{-1}(epsilon) = %.10e\n',zEpsMC);
fprintf('Relative quantile error       = %.4e\n', ...
    abs(zEpsMC-zEps)/max(abs(zEps),realmin));

% Since gamma_inf = Pmax*Omega2*Z2/sigma_D^2, scaling the empirical
% epsilon-quantile of Z2 is exactly equivalent to determining the largest
% target rate that satisfies the empirical outage requirement epsilon.
Rsim_MA = 0.5*log2( ...
    1 + (PmaxLin*Omega2_MA/sigmaD2)*zEpsMC);

Rsim_PA = 0.5*log2( ...
    1 + (PmaxLin*Omega2_PA/sigmaD2)*zEpsMC);

Rsim_FIX = 0.5*log2( ...
    1 + (PmaxLin*Omega2_FIX/sigmaD2)*zEpsMC);

fprintf('\n===== MAX |ANALYSIS - SIMULATION| =====\n');
fprintf('MA    = %.4e bit/s/Hz\n',max(abs(Rmax_MA-Rsim_MA)));
fprintf('PA    = %.4e bit/s/Hz\n',max(abs(Rmax_PA-Rsim_PA)));
fprintf('Fixed = %.4e bit/s/Hz\n',max(abs(Rmax_FIX-Rsim_FIX)));

%% ------------------------------------------------------------------------
% 6) OPTIONAL DIRECT EMPIRICAL-OUTAGE CHECK
% -------------------------------------------------------------------------
% Verify at a few representative Pmax values that the simulated outage
% evaluated at the analytical R0,max is approximately epsilon.

checkDb = [0 10 20 30 40];

fprintf('\n===== EMPIRICAL OUTAGE AT ANALYTICAL R0,max =====\n');

for kk = 1:numel(checkDb)

    [~,idx] = min(abs(PmaxDb-checkDb(kk)));
    Pm = PmaxLin(idx);

    % MA
    gammaInf = Pm*Omega2_MA*Z2mc/sigmaD2;
    thMA = 2^(2*Rmax_MA(idx))-1;
    poutMA = mean(gammaInf < thMA);

    % PA
    gammaInf = Pm*Omega2_PA*Z2mc/sigmaD2;
    thPA = 2^(2*Rmax_PA(idx))-1;
    poutPA = mean(gammaInf < thPA);

    % Fixed
    gammaInf = Pm*Omega2_FIX*Z2mc/sigmaD2;
    thFIX = 2^(2*Rmax_FIX(idx))-1;
    poutFIX = mean(gammaInf < thFIX);

    fprintf(['Pmax/sigma_D^2=%2d dB | ', ...
             'MA %.4e | PA %.4e | Fixed %.4e\n'], ...
             PmaxDb(idx),poutMA,poutPA,poutFIX);
end

%% ------------------------------------------------------------------------
% 7) REVISED IEEE-STYLE FIGURE 5
% -------------------------------------------------------------------------
cMA  = [1.00 0.00 0.00];
cPA  = [0.00 0.00 1.00];
cFIX = [0.00 0.00 0.00];
cSIM = [0.00 0.00 0.00];

fig = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 3.50 2.55]);

ax = axes(fig);
hold(ax,'on');
box(ax,'on');

%% Analytical curves
hMA = plot(ax, ...
    PmaxDb,Rmax_MA,'-', ...
    'Color',cMA, ...
    'LineWidth',0.90, ...
    'DisplayName','Optimized MA');

hPA = plot(ax, ...
    PmaxDb,Rmax_PA,'--', ...
    'Color',cPA, ...
    'LineWidth',0.90, ...
    'DisplayName','Optimized PA');

hFIX = plot(ax, ...
    PmaxDb,Rmax_FIX,':', ...
    'Color',cFIX, ...
    'LineWidth',0.90, ...
    'DisplayName','Fixed positions');

%% Monte-Carlo markers
mk = 1:2:numel(PmaxDb);             % every 4 dB

plot(ax, ...
    PmaxDb(mk),Rsim_MA(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

plot(ax, ...
    PmaxDb(mk),Rsim_PA(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

plot(ax, ...
    PmaxDb(mk),Rsim_FIX(mk),'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'HandleVisibility','off');

%% Dummy simulation handle for legend
hSim = plot(ax, ...
    NaN,NaN,'o', ...
    'LineStyle','none', ...
    'MarkerSize',3.8, ...
    'MarkerFaceColor','none', ...
    'MarkerEdgeColor',cSIM, ...
    'LineWidth',0.70, ...
    'DisplayName','Simulation');

%% epsilon annotation
%% Axis labels
xlabel(ax, ...
    'Normalized saturation power (dB)', ...
    'Interpreter','latex', ...
        'FontSize',10);

ylabel(ax, ...
    'Maximum feasible rate (bit/s/Hz)', ...
    'Interpreter','latex', ...
        'FontSize',10);

xlim(ax,[0 40]);
xticks(ax,0:5:40);

yTop = 1.06*max([Rmax_MA,Rmax_PA,Rmax_FIX]);
ylim(ax,[0 yTop]);

% Clean quarter-bit or half-bit ticks depending on range
if yTop <= 2.5
    stepY = 0.25;
else
    stepY = 0.5;
end
yticks(ax,0:stepY:ceil(yTop/stepY)*stepY);

%% Clean IEEE-style axes/grid
set(ax, ...
    'FontName','Times New Roman', ...
    'FontSize',8, ...
    'TickLabelInterpreter','latex', ...
    'LineWidth',0.70, ...
    'TickDir','in', ...
    'XGrid','on', ...
    'YGrid','on', ...
    'XMinorGrid','off', ...
    'YMinorGrid','off', ...
    'GridAlpha',0.14, ...
    'Layer','top');

%% Legend
lgd = legend(ax, ...
    [hMA hPA hFIX hSim], ...
    'Location','northwest', ...
    'Interpreter','latex', ...
    'FontSize',7, ...
    'Box','on');

lgd.LineWidth = 0.55;
lgd.ItemTokenSize = [20 8];

%% Export
set(fig,'Renderer','painters');

exportgraphics(fig, ...
    'Fig5_Maximum_Feasible_Rate_Revised.pdf', ...
    'ContentType','vector');

exportgraphics(fig, ...
    'Fig5_Maximum_Feasible_Rate_Revised.png', ...
    'Resolution',600);

%% ------------------------------------------------------------------------
% 8) APPEND FIGURE-5 DATA TO MASTER FILE
% -------------------------------------------------------------------------
save(masterFile, ...
    'PmaxDb','PmaxLin','epsilon', ...
    'zEps','zEpsMC', ...
    'Rmax_MA','Rmax_PA','Rmax_FIX', ...
    'Rsim_MA','Rsim_PA','Rsim_FIX', ...
    '-append');

%% ========================================================================
% LOCAL FUNCTION
% ========================================================================

function q = empiricalQuantile(x,p)
% Empirical quantile with linear interpolation between adjacent order
% statistics. This avoids dependence on optional Statistics Toolbox syntax.

x = sort(x(:));
N = numel(x);

% MATLAB-style linear interpolation location
h = 1 + (N-1)*p;

lo = floor(h);
hi = ceil(h);

if lo == hi
    q = x(lo);
else
    q = x(lo) + (h-lo)*(x(hi)-x(lo));
end

end
