%% FIGURE 8: Saturation-induced rotation of the outage landscape
% Analytical contour surfaces from Eq. (30) + Monte-Carlo spot validation
%
% The figure visualizes the optimized outage probability over the joint
% deterministic position-gain plane:
%
%       Omega_1  : source-side deterministic gain
%       Omega_2  : destination-side deterministic gain
%
% at three representative normalized-source-transmit-power regimes:
%       (a) low source power,
%       (b) EH-transition region,
%       (c) saturation regime.
%
% At every (Omega_1,Omega_2) point, rho is optimized over the SAME
% N_rho = 1001 grid used throughout the manuscript.
%
% The contours are obtained from the exact outage representation (30),
% numerically evaluated by Gauss-Legendre quadrature.  Monte-Carlo
% validation is performed at the fixed, optimized-MA, and optimized-PA
% operating points in every panel using 10^6 fading realizations and the
% direct nonlinear-EH/AF equations (7)-(10).
%
% IMPORTANT:
% 1) Run JSAC_Figure02_FINAL.m first.
% 2) Preferably run Fig. 4 before this script; if its transition-SNR values
%    are available in JSAC_Master_Numerical_Data.mat, panel (b) is chosen
%    automatically from those REAL transition results.  Otherwise 22 dB
%    is used as a fallback.
% 3) The MA/PA markers are NOT invented values: they are loaded directly
%    from the same master data generated by Fig. 2.
%
% FIGURE STYLE:
% - two-column IEEE figure, 7.16 in wide
% - restrained pale blue-gray contour shading
% - dark gray analytical contour lines
% - MA marker: red diamond; PA marker: blue triangle; fixed positions: black square
% - Times New Roman / LaTeX labels
% - vector PDF export

clear; clc; close all;

%% ------------------------------------------------------------------------
% 1) LOAD MASTER DATA
% -------------------------------------------------------------------------
% Resolve this script's own folder so shared data are found reliably.
thisScript = mfilename('fullpath');
if isempty(thisScript)
    thisDir = pwd;
else
    thisDir = fileparts(thisScript);
end
masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

% If the shared master data do not yet exist, generate them automatically
% from the finalized Figure-2 program in the same folder.
if ~isfile(masterFile)
    fig2File = fullfile(thisDir,'JSAC_Figure02_FINAL.m');

    if ~isfile(fig2File)
        error(['JSAC_Master_Numerical_Data.mat was not found, and ', ...
               'JSAC_Figure02_FINAL.m is not in the same folder. ', ...
               'Keep all finalized Figure 2-9 programs together.']);
    end

    disp('Shared numerical data were not found.');
    disp('Running finalized Figure 2 first to generate them...');
    run(fig2File);
    close all;

    % Re-establish this script's folder after returning from Figure 2.
    thisScript = mfilename('fullpath');
    if isempty(thisScript)
        thisDir = pwd;
    else
        thisDir = fileparts(thisScript);
    end
    masterFile = fullfile(thisDir,'JSAC_Master_Numerical_Data.mat');

    if ~isfile(masterFile)
        error(['Figure 2 completed, but JSAC_Master_Numerical_Data.mat ', ...
               'was not created in the script folder.']);
    end
end

load(masterFile);

requiredVars = { ...
    'Omega1_MA','Omega2_MA', ...
    'Omega1_PA','Omega2_PA', ...
    'M1','M2'};

for k = 1:numel(requiredVars)
    if ~exist(requiredVars{k},'var')
        error('Required variable "%s" is missing from %s.', ...
              requiredVars{k},masterFile);
    end
end

Omega1_FIX = 1;
Omega2_FIX = 1;

%% ------------------------------------------------------------------------
% 2) TABLE-II / MANUSCRIPT PARAMETERS
% -------------------------------------------------------------------------
sigmaR2 = 1;
sigmaD2 = 1;

Pmax = sigmaD2*10^(13/10);      % Pmax/sigma_D^2 = 13 dB
bEH  = sigmaR2*10^(10/10);      % bEH/sigma_R^2 = 10 dB
aEH  = 0.5/sigmaR2;             % aEH*sigma_R^2 = 0.5
xi0  = 1/(1+exp(aEH*bEH));

R0 = 1;
gammaTh = 2^(2*R0)-1;

rhoMin = 0.01;
Nrho = 1001;
rhoGrid = linspace(rhoMin,1-rhoMin,Nrho);

Nmc = 1e6;

% Default Log-alpha-mu tuple
alpha1 = 2; beta1 = 1; mu1 = 2; s1 = 0.5;
alpha2 = 2; beta2 = 1; mu2 = 2; s2 = 0.5;

p.alpha1=alpha1; p.beta1=beta1; p.mu1=mu1; p.s1=s1; p.M1=M1;
p.alpha2=alpha2; p.beta2=beta2; p.mu2=mu2; p.s2=s2; p.M2=M2;
p.sigmaR2=sigmaR2; p.sigmaD2=sigmaD2;
p.Pmax=Pmax; p.bEH=bEH; p.aEH=aEH; p.xi0=xi0;
p.gammaTh=gammaTh;

%% ------------------------------------------------------------------------
% 3) SELECT THE THREE SOURCE-TRANSMIT-SNR REGIMES
% -------------------------------------------------------------------------
snrLow = 10;
snrHigh = 40;

% If Fig. 4 has already been run, use the REAL MA/PA crossing information
% to choose a representative transition-region SNR.
crossings = [];

if exist('snrCross_MA','var') && isfinite(snrCross_MA)
    crossings(end+1) = snrCross_MA; %#ok<SAGROW>
end

if exist('snrCross_PA','var') && isfinite(snrCross_PA)
    crossings(end+1) = snrCross_PA; %#ok<SAGROW>
end

if isempty(crossings)
    snrMid = 22;                  % fallback only
    fprintf(['Fig. 4 crossing data were not found. ', ...
             'Using 22 dB as the transition-panel fallback.\n']);
else
    snrMid = 2*round(mean(crossings)/2);
    snrMid = min(max(snrMid,12),32);
end

snrPanels = [snrLow snrMid snrHigh];

fprintf('\n===== FIG. 8 SOURCE-TRANSMIT-SNR PANELS =====\n');
fprintf('Low-power panel      : %.1f dB\n',snrPanels(1));
fprintf('Transition panel     : %.1f dB\n',snrPanels(2));
fprintf('Saturation panel     : %.1f dB\n',snrPanels(3));

%% ------------------------------------------------------------------------
% 4) JOINT POSITION-GAIN PLANE
% -------------------------------------------------------------------------
% Keep the same useful physical range as the current manuscript figure.
% The explicit MA/PA optimized points loaded from Fig. 2 are guaranteed
% to be included; the limits expand automatically if ever necessary.

g1MarkerDb = 10*log10([Omega1_MA Omega1_PA Omega1_FIX]);
g2MarkerDb = 10*log10([Omega2_MA Omega2_PA Omega2_FIX]);

g1MaxDb = max(8,ceil(max(g1MarkerDb)+1));
g2MaxDb = max(12,ceil(max(g2MarkerDb)+1));

% Moderately fine contour grid.  The rho search itself remains N_rho=1001.
g1Db = linspace(0,g1MaxDb,33);
g2Db = linspace(0,g2MaxDb,37);

g1Lin = 10.^(g1Db/10);
g2Lin = 10.^(g2Db/10);

% A fixed order is used for the dense contour surface.
% Independent adaptive high-order checks are performed at the marked
% operating points below.
NqSurface = 128;
[xGLsurf,wGLsurf] = gaussLegendre(NqSurface);

%% ------------------------------------------------------------------------
% 5) ANALYTICAL OUTAGE LANDSCAPES
% -------------------------------------------------------------------------
nPanels = numel(snrPanels);

Psurf = cell(1,nPanels);
rhoSurf = cell(1,nPanels);

fprintf('\n===== ANALYTICAL OUTAGE LANDSCAPES =====\n');

for m = 1:nPanels

    fprintf('Computing panel %d/%d at %.1f dB ...\n', ...
        m,nPanels,snrPanels(m));

    [Psurf{m},rhoSurf{m}] = outageLandscape( ...
        snrPanels(m),rhoGrid,g1Lin,g2Lin,p,xGLsurf,wGLsurf);

    fprintf('  minimum outage on plane = %.6e\n',min(Psurf{m},[],'all'));
    fprintf('  maximum outage on plane = %.6e\n',max(Psurf{m},[],'all'));
end

%% ------------------------------------------------------------------------
% 6) MONTE-CARLO SPOT VALIDATION AT THE MARKED OPERATING POINTS
% -------------------------------------------------------------------------
% The contour map itself is analytical.  To validate it independently,
% use direct Eqs. (7)-(10) at:
%   1) fixed benchmark,
%   2) optimized MA point,
%   3) optimized PA point,
% for all three normalized-source-transmit-power panels.

rng(20260910,'twister');

r1 = @(u) ...
    ((1+beta1*u/mu1).^(1/beta1)-s1).^(1/alpha1) ...
    -(1-s1)^(1/alpha1);

r2 = @(u) ...
    ((1+beta2*u/mu2).^(1/beta2)-s2).^(1/alpha2) ...
    -(1-s2)^(1/alpha2);

U1mc = randg(mu1,Nmc,1);
U2mc = randg(mu2,Nmc,1);

Z1mc = r1(U1mc).^2/M1;
Z2mc = r2(U2mc).^2/M2;

spotNames = {'Fixed','Optimized MA','Optimized PA'};

spotOmega1 = [ ...
    Omega1_FIX, ...
    Omega1_MA, ...
    Omega1_PA];

spotOmega2 = [ ...
    Omega2_FIX, ...
    Omega2_MA, ...
    Omega2_PA];

PspotAna = zeros(nPanels,3);
PspotSim = zeros(nPanels,3);
rhoSpot = zeros(nPanels,3);

GLordersCheck = [64 128 256 512];
relTol = 1e-9;
absTol = 1e-12;

fprintf('\n===== MONTE-CARLO SPOT VALIDATION =====\n');

for m = 1:nPanels

    Ps = sigmaR2*10^(snrPanels(m)/10);

    fprintf('\nPanel %d: normalized source transmit power = %.1f dB\n',m,snrPanels(m));

    for s = 1:3

        [PspotAna(m,s),rhoSpot(m,s)] = optimizeRhoAdaptive( ...
            snrPanels(m),spotOmega1(s),spotOmega2(s), ...
            rhoGrid,p,GLordersCheck,relTol,absTol);

        PspotSim(m,s) = directMonteCarloOutage( ...
            Ps,rhoSpot(m,s),spotOmega1(s),spotOmega2(s), ...
            Z1mc,Z2mc,p);

        fprintf(['  %-12s | rho*=%.3f | Analysis %.6e | ', ...
                 'Simulation %.6e | abs.err %.3e\n'], ...
                 spotNames{s},rhoSpot(m,s), ...
                 PspotAna(m,s),PspotSim(m,s), ...
                 abs(PspotAna(m,s)-PspotSim(m,s)));
    end
end

fprintf('\nMaximum spot-check |Analysis-Simulation| = %.4e\n', ...
    max(abs(PspotAna-PspotSim),[],'all'));

%% ------------------------------------------------------------------------
% 7) REVISED LOW-COLOR IEEE-STYLE FIGURE 8
% -------------------------------------------------------------------------
% Architecture colors: MA red, PA blue, fixed positions black.
cMA  = [1.00 0.00 0.00];
cPA  = [0.00 0.00 1.00];
cFIX = [0.00 0.00 0.00];

% Soft blue-gray colormap: deliberately low saturation.
nMap = 256;

cStart = [0.985 0.990 0.993];
cEnd   = [0.62  0.72  0.77];

softMap = [ ...
    linspace(cStart(1),cEnd(1),nMap).', ...
    linspace(cStart(2),cEnd(2),nMap).', ...
    linspace(cStart(3),cEnd(3),nMap).' ];

% Common outage contour levels across all panels.
levels = [0.02 0.03 0.05 0.08 0.12 0.20 0.35 0.55 0.80];

fig = figure( ...
    'Color','w', ...
    'Units','inches', ...
    'Position',[1 1 7.16 2.70]);

tl = tiledlayout(fig,1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

colormap(fig,softMap);

panelTitle = { ...
    '(a) Low', ...
    '(b) Transition', ...
    '(c) Saturation'};

for m = 1:nPanels

    ax = nexttile(tl,m);
    hold(ax,'on');
    box(ax,'on');

    % Light analytical filled contours
    contourf(ax, ...
        g1Db,g2Db,Psurf{m}.', ...
        levels, ...
        'LineStyle','none');

    % Dark-gray analytical contour lines
    [C,hC] = contour(ax, ...
        g1Db,g2Db,Psurf{m}.', ...
        levels, ...
        'LineColor',[0.28 0.31 0.33], ...
        'LineWidth',0.60);

    clabel(C,hC, ...
        'FontName','Times New Roman', ...
        'FontSize',5.8, ...
        'Color',[0.24 0.24 0.24], ...
        'LabelSpacing',260);

    % Fixed benchmark
    hFIX = plot(ax, ...
        0,0,'s', ...
        'LineStyle','none', ...
        'MarkerSize',4.5, ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',cFIX, ...
        'LineWidth',0.90, ...
        'DisplayName','Fixed positions');

    % Optimized MA
    hMA = plot(ax, ...
        10*log10(Omega1_MA), ...
        10*log10(Omega2_MA),'d', ...
        'LineStyle','none', ...
        'MarkerSize',4.8, ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',cMA, ...
        'LineWidth',0.90, ...
        'DisplayName','Optimized MA');

    % Optimized PA
    hPA = plot(ax, ...
        10*log10(Omega1_PA), ...
        10*log10(Omega2_PA),'^', ...
        'LineStyle','none', ...
        'MarkerSize',5.0, ...
        'MarkerFaceColor','none', ...
        'MarkerEdgeColor',cPA, ...
        'LineWidth',0.90, ...
        'DisplayName','Optimized PA');

    xlabel(ax, ...
        'Source-side gain (dB)', ...
        'Interpreter','latex', ...
            'FontSize',10);

    if m == 1
        ylabel(ax, ...
            'Destination-side gain (dB)', ...
            'Interpreter','latex', ...
                'FontSize',10);
    end

    title(ax, ...
        sprintf('%s: %.0f dB',panelTitle{m},snrPanels(m)), ...
        'Interpreter','latex', ...
        'FontWeight','normal', ...
        'FontSize',7.2);

    % Small white margin keeps the fixed marker visible at (0,0).
    xlim(ax,[-0.25 g1MaxDb]);
    ylim(ax,[-0.35 g2MaxDb]);

    xticks(ax,0:2:g1MaxDb);
    yticks(ax,0:2:g2MaxDb);

    set(ax, ...
        'FontName','Times New Roman', ...
        'FontSize',8, ...
        'TickLabelInterpreter','latex', ...
        'LineWidth',0.70, ...
        'TickDir','in', ...
        'XGrid','off', ...
        'YGrid','off', ...
        'Layer','top');
end

%% Shared legend below all three panels
% IMPORTANT MATLAB compatibility fix:
% legend() cannot use a TiledChartLayout object as the target in many
% MATLAB releases.  Create the legend from the LAST axes (whose three
% marker handles are hFIX, hMA, and hPA), then assign the legend to the
% tiled layout's south tile.
lgd = legend(ax, ...
    [hFIX hMA hPA], ...
    'Orientation','horizontal', ...
    'Interpreter','latex', ...
    'FontSize',7, ...
    'Box','on');

lgd.LineWidth = 0.55;
lgd.ItemTokenSize = [16 8];
lgd.Layout.Tile = 'south';

%% Export
set(fig,'Renderer','painters');

exportgraphics(fig, ...
    'Fig8_Outage_Landscape_Rotation_Revised.pdf', ...
    'ContentType','vector');

exportgraphics(fig, ...
    'Fig8_Outage_Landscape_Rotation_Revised.png', ...
    'Resolution',600);

%% ------------------------------------------------------------------------
% 8) APPEND FIGURE-8 DATA TO MASTER FILE
% -------------------------------------------------------------------------
save(masterFile, ...
    'snrPanels', ...
    'g1Db','g2Db','g1Lin','g2Lin', ...
    'Psurf','rhoSurf', ...
    'PspotAna','PspotSim','rhoSpot', ...
    'NqSurface', ...
    '-append');

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function [Pbest,rhoBest] = outageLandscape( ...
    snrDb,rhoGrid,g1Lin,g2Lin,p,xGL,wGL)
% Optimized analytical outage surface over the joint (Omega1,Omega2) plane.
%
% For each rho:
%   - Eq. (30) is evaluated for all source-side gains,
%   - the second-hop CDF is evaluated for all destination-side gains,
%   - the best outage over the N_rho grid is retained.

Ps = p.sigmaR2*10^(snrDb/10);

n1 = numel(g1Lin);
n2 = numel(g2Lin);
Nq = numel(xGL);

Pbest = ones(n1,n2);
rhoBest = nan(n1,n2);

g1 = g1Lin(:);                 % n1 x 1
g2 = reshape(g2Lin,1,1,n2);    % 1 x 1 x n2

w3 = reshape(wGL(:),1,Nq,1);

for ir = 1:numel(rhoGrid)

    rho = rhoGrid(ir);

    kappa = (1-rho)*Ps/p.sigmaR2;
    xth = p.gammaTh/kappa;

    uth = p.mu1*PsiFun( ...
        sqrt(p.M1*xth./g1), ...
        p.alpha1,p.beta1,p.s1);

    pth = gammainc(uth,p.mu1,'lower');

    % Map GL nodes from [-1,1] to [pth,1].
    v = (1+pth)/2 + ((1-pth)/2).*xGL(:).';

    v = min(v,1-eps);
    v = max(v,realmin);

    u = gammaincinv(v,p.mu1,'lower');

    r = ...
        ((1+p.beta1*u/p.mu1).^(1/p.beta1)-p.s1) ...
        .^(1/p.alpha1) ...
        -(1-p.s1)^(1/p.alpha1);

    x = g1.*r.^2/p.M1;         % n1 x Nq

    Pin = rho*Ps.*x;
    PH = EHmap(Pin,p);

    nu = PH/p.sigmaD2;

    den = nu.*(kappa*x-p.gammaTh);

    T = inf(size(x));
    good = den > 0;

    num = p.gammaTh*(kappa*x+1);
    T(good) = num(good)./den(good);

    % n1 x Nq x n2
    arg = reshape(T,n1,Nq,1)./g2;

    FY = FZ( ...
        arg, ...
        p.alpha2,p.beta2,p.mu2,p.s2,p.M2);

    integralPart = squeeze(sum(FY.*w3,2));   % n1 x n2

    if n2 == 1
        integralPart = integralPart(:);
    end

    current = ...
        pth + ((1-pth)/2).*integralPart;

    current = min(max(current,0),1);

    improve = current < Pbest;

    Pbest(improve) = current(improve);
    rhoBest(improve) = rho;
end

end

%% ------------------------------------------------------------------------

function [Pbest,rhoBest,Nused] = optimizeRhoAdaptive( ...
    snrDb,Omega1,Omega2,rhoGrid,p,orders,relTol,absTol)
% High-accuracy adaptive evaluation at a single marked operating point.

prevBest = NaN;
Pbest = NaN;
rhoBest = NaN;
Nused = orders(end);

for ii = 1:numel(orders)

    N = orders(ii);
    [xGL,wGL] = gaussLegendre(N);

    Pvec = outageGLgrid( ...
        snrDb,rhoGrid,Omega1,Omega2,p,xGL,wGL);

    [currBest,idx] = min(Pvec);
    currRho = rhoGrid(idx);

    if ii > 1

        err = abs(currBest-prevBest);
        tol = absTol + relTol*abs(currBest);

        if err <= tol
            Pbest = currBest;
            rhoBest = currRho;
            Nused = N;
            return;
        end
    end

    prevBest = currBest;
    Pbest = currBest;
    rhoBest = currRho;
end

warning(['Gauss-Legendre convergence target was not reached ', ...
         'by N=%d at SNR %.1f dB. Highest-order result is used.'], ...
         orders(end),snrDb);

end

%% ------------------------------------------------------------------------

function Pout = outageGLgrid( ...
    snrDb,rhoGrid,Omega1,Omega2,p,xGL,wGL)
% Finite-order evaluation of Eq. (30) over all rho values.

Ps = p.sigmaR2*10^(snrDb/10);

rho = rhoGrid(:);
kappa = (1-rho)*Ps/p.sigmaR2;

xth = p.gammaTh./kappa;

uth = p.mu1*PsiFun( ...
    sqrt(p.M1*xth/Omega1), ...
    p.alpha1,p.beta1,p.s1);

pth = gammainc(uth,p.mu1,'lower');

Pout = ones(size(rho));

active = find(pth < 1-1e-14);

if isempty(active)
    return;
end

pa = pth(active);
ka = kappa(active);

v = (1+pa)/2 + ((1-pa)/2).*xGL(:).';

v = min(v,1-eps);
v = max(v,realmin);

u = gammaincinv(v,p.mu1,'lower');

r = ...
    ((1+p.beta1*u/p.mu1).^(1/p.beta1)-p.s1) ...
    .^(1/p.alpha1) ...
    -(1-p.s1)^(1/p.alpha1);

x = Omega1*r.^2/p.M1;

Pin = rho(active).*Ps.*x;
PH = EHmap(Pin,p);

nu = PH/p.sigmaD2;

den = nu.*(ka.*x-p.gammaTh);

T = inf(size(x));
good = den > 0;

num = p.gammaTh*(ka.*x+1);
T(good) = num(good)./den(good);

FY = FZ( ...
    T/Omega2, ...
    p.alpha2,p.beta2,p.mu2,p.s2,p.M2);

integralPart = sum(FY.*wGL(:).',2);

Pout(active) = ...
    pa + ((1-pa)/2).*integralPart;

Pout = min(max(Pout,0),1);

end

%% ------------------------------------------------------------------------

function Pout = directMonteCarloOutage( ...
    Ps,rho,Omega1,Omega2,Z1,Z2,p)
% Direct nonlinear-EH AF simulation from Eqs. (7)-(10).

X = Omega1*Z1;
Y = Omega2*Z2;

Pin = rho*Ps.*X;
PH = EHmap(Pin,p);

gamma1 = ...
    (1-rho)*Ps.*X/p.sigmaR2;

gamma2 = ...
    PH.*Y/p.sigmaD2;

gammaE2E = ...
    (gamma1.*gamma2)./(gamma1+gamma2+1);

Pout = mean(gammaE2E < p.gammaTh);

end

%% ------------------------------------------------------------------------

function PH = EHmap(Pin,p)
% Eq. (7)

PH = ...
    (p.Pmax./(1+exp(-p.aEH*(Pin-p.bEH))) ...
    -p.Pmax*p.xi0)/(1-p.xi0);

PH = max(PH,0);

end

%% ------------------------------------------------------------------------

function F = FZ(z,alpha,beta,mu,s,M)
% Eq. (13)

z = max(z,0);

u = mu*PsiFun( ...
    sqrt(M*z), ...
    alpha,beta,s);

F = gammainc(u,mu,'lower');

end

%% ------------------------------------------------------------------------

function y = PsiFun(r,alpha,beta,s)
% Eq. (12)

c = (1-s)^(1/alpha);

y = ...
    (((r+c).^alpha+s).^beta-1)/beta;

end

%% ------------------------------------------------------------------------

function [x,w] = gaussLegendre(N)
% Standard N-point Gauss-Legendre nodes and weights on [-1,1].

k = (1:N-1)';

b = k./sqrt(4*k.^2-1);

J = diag(b,1)+diag(b,-1);

[V,D] = eig(J);

[x,idx] = sort(diag(D));

V = V(:,idx);

w = 2*(V(1,:)').^2;

end
